FROM python:3.12-slim@sha256:af4e85f1cac90dd3771e47292ea7c8a9830abfabbe4faa5c53f158854c2e819d

RUN pip install --no-cache-dir flask==3.1.1 sqlalchemy==2.0.41 pytest==8.3.5 \
    && useradd -m -u 1000 runner

USER runner
WORKDIR /app

CMD ["python", "/app/code.py"]
